version: '2.1'
services:

  webapp:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
#          condition: service_healthy
    command: flask run --host 0.0.0.0 --port 8000

  database:
      image: postgres:13
      env_file: .env
      expose:
        - 5432
      ports:
        - "5432:5432"